# Human-readable module metadata.
# ABK reads this file to validate and prefill module options.

ABK_MODULE_ID="8Gen3_Gunyah_Fix"
ABK_MODULE_NAME="8Gen3_Gunyah_Fix"
ABK_MODULE_VERSION="1"
ABK_MODULE_DESCRIPTION="Patch Kernel To Fix Gunyah On 8Gen3"
ABK_MODULE_REPO_URL="https://github.com/ExpressZ53/8Gen3_Gunyah_Fix"
ABK_MODULE_SUPPORTED_STAGES="after_patch"
ABK_MODULE_DEFAULT_STAGE="after_patch"
ABK_MODULE_RECOMMENDED_STAGES="after_patch"